CREATE DATABASE IF NOT EXISTS paw
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON paw.* TO 'paw'@'localhost'
IDENTIFIED BY 'mysqlPassword';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON paw.* TO 'paw'@'%'
IDENTIFIED BY 'mysqlPassword'
WITH GRANT OPTION;
FLUSH PRIVILEGES;
USE paw;
